# 产品或项目名称、软件开发公司名称
productName: 档案管理中心
companyName: bainiu

# 产品版本、版权年份
productVersion: V1.0
copyrightYear: 2021

#是否演示模式
demoMode: false

server:
  port: 8980
  servlet:
    context-path: /dangan
  tomcat:
    uri-encoding: UTF-8
    
  # 将请求协议转换为 https
  schemeHttps: false
    
# 数据库连接
jdbc: 
  
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/jeesite?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
  username: root
  password: 123456
  testSql: select 1

# Web 相关
web:
  # MVC 视图相关
  view:
    themeName: default

spring:
  
  # 应用程序名称
  application:
    name: talent
    
  # 环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default
    
  # 打印横幅
  main:
    bannerMode: "off"
    
logging:
  config: classpath:config/logback-spring.xml

# Shiro 相关配置
shiro:
  rememberMe:
    secretKey: ~


App:
  phoneVersion: 2.1.0
  tabletVersion: 2.1.0

